homework3/django/src/front/urls.py
"""
Poll's module urls
"""
from django.urls import path
from django.conf.urls import include

from . import views

# pylint: disable=invalid-name
app_name = 'front'

# pylint: disable=invalid-name
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail')
]

homework3/django/src/store/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.http import HttpResponse

urlpatterns = [
    path('robots.txt', lambda request: HttpResponse()),
    path('', include('front.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.default.urls')),
]

homework3/django/src/front/models.py
"""
Store models
"""
import datetime

from django.db import models
from django.utils import timezone


class Good(models.Model):
    """
    Good model
    """
    name = models.CharField(max_length=200)
    price = models.IntegerField(default=100)
    pub_date = models.DateTimeField('date published')

    # pylint: disable=missing-docstring
    def __str__(self):
        return self.name

    def was_published_recently(self):
        """
        Was a good published recently (last day)

        :return: boolean
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

homework3/django/src/orders/models.py
from django.db import models

# Create your models here.

homework3/django/src/front/views.py
"""
Poll views
"""
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Good


# pylint: disable=too-many-ancestors
class IndexView(generic.ListView):
    """
    Index view
    """
    template_name = 'goods/index.html'
    context_object_name = 'goods'

    def get_queryset(self):
        """Return the last five published goods."""
        return Good.objects.order_by('-pub_date')[:10]


class DetailView(generic.DetailView):
    """
    Good details view
    """
    model = Good
    template_name = 'goods/detail.html'

homework3/django/src/orders/views.py
from django.shortcuts import render

# Create your views here.

homework3/django/src/front/templates/base.html
<html>
<head>
<title>{% block title %}Django Shop{% endblock title %}</title>
    {% block meta %}{% endblock meta %}
</head>
<body>
  <header>
    <div>
      {% if request.user.id == None %}
      <a href="/accounts/login/">Login</a>
      <hr/>
      {% endif %}
      {% block breadcrumbs %}
      {% endblock breadcrumbs %}
    </div>
    <h1>{% block header %}{% endblock header %}</h1>
  </header>
  {% block content %}{% endblock content %}
  <footer>
    <hr>
    No rights reserved. No services served.
  </footer>
</body>
</html>

homework3/django/src/front/templates/goods/detail.html
{% extends "base.html" %}
{% block title %}Django Shop - {{ good.name }}{% endblock %}
{% block breadcrumbs %}
  <div>
    <a href="{% url 'front:index' %}">Goods</a>
    <br />
    <hr />
  </div>
{% endblock breadcrumbs %}
{% block header %}{{ good.name }}{% endblock header %}
{% block content %}
<h2>{{ good.price }} points</h2>
<p>There should be the product's description, but I'm too lazy for this.</p>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if request.user.id != None %}
Call <a href="tel:+380680000000">+380(68)00-00-000</a>
 and say "I'm user {{ request.user.id }} and I want to order a product
 number {{ good.id }}".
{% else %}
<a href="/accounts/login/">You should login before taking an order</a>
{% endif %}
{% endblock content %}

homework3/django/src/front/templates/goods/index.html
{% extends "base.html" %}
{% block title %}Django Shop - Goods{% endblock title %}
{% block header %}Our goods{% endblock header %}
{% block content %}
  {% if goods %}
    <ul>
    {% for good in goods %}
      <li>
        <a href="{% url 'front:detail' good.id %}">{{ good.name }}</a>
        - {{ good.price }} points
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No goods are available.</p>
  {% endif %}
{% endblock content %}